stages:
  - validate
  - deploy

variables:
  ANSIBLE_HOST_KEY_CHECKING: "False"
  ANSIBLE_FORCE_COLOR: "True"

default:
  before_script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install --quiet ansible
    - pip install paramiko
    - ansible-galaxy collection install -r requirements.yml

validate:
  stage: validate
  script:
    - ansible-playbook playbooks/validate.yml --check --diff
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

deploy:
  stage: deploy
  script:
    - ansible-playbook playbooks/site.yml
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual

