ansible_network_os: arista.eos.eos
ansible_connection: ansible.netcommon.network_cli
ansible_become: true
ansible_become_method: enable
ansible_user: "michael"
ansible_password: "michael1"
ansible_become_password: "michael1"

ntp_server: 192.168.0.1
syslog_server: 192.168.0.1
mgmt_interface: Management1
