---
- name: Validate common configuration (check mode)
  hosts: fabric
  gather_facts: false
  roles:
    - role: common
      tags: common

- name: Validate underlay (check mode)
  hosts: fabric
  gather_facts: false
  roles:
    - role: underlay
      tags: underlay

- name: Validate overlay and VLANs (check mode)
  hosts: leaves
  gather_facts: false
  roles:
    - role: vlans
      tags: vlans
    - role: overlay
      tags: overlay
