---
- name: Push underlay configuration (spines)
  arista.eos.eos_config:
    src: underlay_spine.j2
  when: node_role == 'spine'
  tags: underlay

- name: Push underlay configuration (leaves)
  arista.eos.eos_config:
    src: underlay_leaf.j2
  when: node_role == 'leaf'
  tags: underlay
